[global]
   workgroup = MYGROUP
   server string = Samba Server
   server role = standalone server
   log file = /dev/stdout
   max log size = 50
   dns proxy = no
   map to guest = bad user
   create mask = 0664
   force create mode = 0664
   directory mask = 0775
   force directory mode = 0775
   follow symlinks = yes
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes
   strict locking = no
   client min protocol = SMB2
   server min protocol = SMB2

[media]
   path = /media
   browsable = yes
   read only = no
   guest ok = no
   valid users = evan

[general]
   path = /general
   browsable = yes
   read only = no
   guest ok = no
   valid users = evan, karla
   write list = evan, karla
